# storage parameter
Tennis: 'UnityEnvs/Tennis_Linux/Tennis.x86_64'

# training params MADDPG
Episodes: 5000
BufferSize: 100000
LearningRateActor: 1e-4
LearningRateCritic: 1e-4
BatchesSizeMADDPG: 512

# next test with lr both 1e-3, batch 512, noise sigma 0.1, hidden layers all 64, tau 1e-2, gamma 0.95
# best run lr both 1e-4, batch 512, noise sigma 0.1, hidden layers all 64, tau 1e-2, gamma 0.95